version: '3'

services:
  # Backend (Laravel)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - storage-volume:/var/www/html/storage
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3306"
    depends_on:
      - db
    ports:
      - "8001:80"

  # Frontend (Vue.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/src:/app/src

  # Base de Datos (MySQL)
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  dbdata:
  storage-volume:
